remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-redirect-from

baseurl: /leap-day
permalink: none
collections:
  tags:
    output: true
    permalink: tags/:path/

defaults:
  -
    values:
      # author: "刘杰文"
      # title: "leap-day | Document"
      layout: leap_day_customized_v5.1.1
      # allow_download_doc: true

author: "刘杰文"
allow_download_doc: true

whitelist:
  - jekyll-remote-theme
  - jekyll-redirect-from
  